import Head from "next/head";
import Cards from "../components/cards";
import styled from "styled-components";
import Filter from "../components/filter";
import GET_VIDEOS from "../gql/queries/getVideos";
import { ApolloError, useQuery } from "@apollo/client";
import { useRouter } from "next/router";
import { useEffect } from "react";
import FilterBtn from "../components/filterBtn";
import Navbar from "../components/navbar";
import client from "../gql/apolloclient";
import { Video } from "../gql/types";

type Props = {
  loading: boolean;
  error: ApolloError | undefined;
  data: {
    videos: {
      totalCount: number;
      data: Video[];
      page: number;
    };
  };
};

const Videos = (props: Props) => {
  const { query } = useRouter();
  const {
    data: clientSideRendredData,
    error,
    fetchMore,
    refetch,
  } = useQuery(GET_VIDEOS, {
    variables: {
      perPage: 9,
      query: "",
    },
  });
  const { data, loading } = props;

  const videos = data?.videos?.data;

  useEffect(() => {
    refetch({ query: query.q as string });
  }, [query, refetch]);

  if (loading && !videos) return null;
  if (error) return `Error! ${error.message}`;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <Container>
        <Filter />
        <FilterBtn />
        <Cards
          loadMore={() => {
            console.log("fetchMore");
            return fetchMore({
              variables: {
                page: data.videos.page + 1,
              },
            });
          }}
          data={clientSideRendredData}
        />
      </Container>
    </div>
  );
};

export async function getServerSideProps() {
  // Fetch data from external API
  const { loading, data } = await client.query({
    query: GET_VIDEOS,
    variables: {
      perPage: 9,
      query: "",
    },
  });
  // Pass data to the page via props
  return { props: { data, loading } };
}

export default Videos;

const Container = styled.div`
  display: flex;
  justify-content: center;
  align-items: center;
  flex-direction: column;
  max-width: 1200px;
  margin: 2em auto;
  padding: 0 1em;
`;
